name: CI

on:
  push:
    branches:
      - main
      - tests
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: echo "ID_KEY=${{ secrets.ID_KEY }}" >> $GITHUB_ENV
        
      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test